version: '3.7'

volumes:
  mymicroservice_7_sqldata:
  mymicroservice_7_elasticdata:
  mymicroservice_7_rabbitmq:
networks:
  mymicroservice_7:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    volumes:
      - mymicroservice_7_rabbitmq:/var/lib/rabbitmq
    networks:
      - mymicroservice_7
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: redis
    image: redis:7.2.2-alpine
    networks:
      - mymicroservice_7
    ports:
      - "6379:6379"
      
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    volumes:
      - mymicroservice_7_elasticdata:/usr/share/elasticsearch/data
    networks:
      - mymicroservice_7
    environment:
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.4
    depends_on:
      - elasticsearch
    networks:
      - mymicroservice_7
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
    ports: 
      - "5601:5601"
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    volumes:
      - mymicroservice_7_sqldata:/var/opt/mssql
      - mymicroservice_7_sqldata:/var/opt/mssql-extensibility
      - mymicroservice_7_sqldata:/var/opt/mssql-extensibility/log
      - mymicroservice_7_sqldata:/var/opt/mssql-extensibility/data
    networks:
      - mymicroservice_7
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw@rd"
      ACCEPT_EULA: "Y"
  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.0
    volumes:
      - ./grafana/storage:/var/lib/grafana
    networks:
      - mymicroservice_7
    ports:
      - "3001:3000"
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus/storage:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mymicroservice_7
    ports:
      - "9090:9090"